// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	// Trivial liveness query — lets the healthcheck handler prove the DB
	// connection is actually alive (not just that it was pingable once,
	// at boot, in database.NewPool). Also the minimum sqlc needs to
	// generate a real Queries/Querier type with zero domain tables.
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
