// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ping.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1
`

// Trivial liveness query — lets the healthcheck handler prove the DB
// connection is actually alive (not just that it was pingable once,
// at boot, in database.NewPool). Also the minimum sqlc needs to
// generate a real Queries/Querier type with zero domain tables.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
